name: 'alshdavid/setup-rust'
description: "Install Rust"

runs:
  using: 'composite'
  steps:
    - name: "Install Rust" 
      if: ${{ runner.os != 'Windows' }}
      shell: bash
      env:
        NODE_VERSION: ${{ inputs.version }}
      run: "bash .github/actions/setup-rust/install-rust.bash"

    - name: "Install Rust" 
      if: ${{ runner.os == 'Windows' && runner.arch == 'X64' }}
      shell: powershell
      env:
        NODE_VERSION: ${{ inputs.version }}
      run: . .github/actions/setup-rust/install-rust.ps1
