#!/bin/bash

function default() 
{
  build
}

function build() 
{
  # if [[ $@ =~ "--release" ]]; then
  #   echo hasit
  # fi
  cargo build $@
}

function test() 
{
  echo soon
}

function fmt() 
{
  cargo +nightly fmt
}

function fixture-serve() 
{
	test -d node_modules || pnpm install
	cd fixtures/${1} 
  pnpm run serve
}

function fixture-build() 
{
	test -d node_modules || pnpm install
  ARGS="${@:2}"
  cd fixtures/${1}
	test -f ./src/index.jsx && cargo run --bin mach -- ./src/index.jsx $ARGS || true
	test -f ./src/index.js && cargo run --bin mach -- ./src/index.js $ARGS || true
	test -f ./src/index.tsx && cargo run --bin mach -- ./src/index.tsx $ARGS || true
	test -f ./src/index.ts && cargo run --bin mach -- ./src/index.ts $ARGS || true
}

${1:-default} "${@:2}"
