BIN_VERSION := env_var_or_default("BIN_VERSION", "")
profile := env_var_or_default("profile", "debug")
target := env_var_or_default("target", "")

build:
  just _create_out_dir
  cargo build \
    {{ if profile != "debug" { "--profile " + profile } else { "" } }} \
    {{ if target != "" { "--target " + target } else { "" } }}
  just _copy_cargo

_create_out_dir:
  mkdir -p ../../target/{{profile}}/adapters/nodejs

_copy_cargo:
  cp ../../target/.cargo/{{profile}}/libmach_adapter_nodejs.so ../../target/{{profile}}/adapters/nodejs/lib.so
