name: 'alshdavid/build-npm'
description: "Build Project"

inputs:
  os:
    description: 'target operating system'
    default: ${{ runner.os == 'Linux' && 'linux' || runner.os == 'macOS' && 'macos' || runner.os == 'Windows' && 'windows' }}
  arch:
    description: 'target CPU architecture'
    default: ${{ runner.arch == 'ARM64' && 'arm64' || runner.arch == 'X64' && 'amd64' }}
  profile:
    description: 'Build profile'
    default: "release"
  mach_version:
    description: 'prepare packages for publishing'
    default: ''

runs:
  using: 'composite'
  steps:
    - name: "Build Project" 
      shell: bash
      env:
        os: "${{inputs.os}}"
        arch: "${{inputs.arch}}"
        MACH_VERSION: "${{inputs.mach_version}}"
        profile: "${{inputs.profile}}"
      run: |
        source .github/workflows/platform/unix/setup-env.bash
        bash .github/actions/build-npm/build.bash

  - name: "Copy Artifacts" 
      shell: bash
      if: inputs.mach_version != ''
      env:
        os: "${{inputs.os}}"
        arch: "${{inputs.arch}}"
        MACH_VERSION: "${{inputs.mach_version}}"
        profile: "${{inputs.profile}}"
      run: |
        source .github/workflows/platform/unix/setup-env.bash
        bash .github/actions/build-npm/build.bash
    
    