[package]
name = "mach_adapter_deno"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
libmach = { path = "../../crates/libmach" }

[profile.release-lto]
inherits = "release"
lto = true
