[package]
name = "mach_bundler_npm_os_arch"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "./src/lib.rs"

[dependencies]
mach_bundler_core = { path = "../mach", features = ["cli_parser", "rpc_nodejs"] }
anyhow = "1"
napi = { version = "2.*", default-features = false, features = ["napi8", "tokio_rt", "serde-json", "async"] }
napi-derive = "2.*"
serde = { version = "1.*", features = ["derive"] }
once_cell = "1.*"
parking_lot = "0.*"
tokio = { version = "1.*", features = ["full"] }

[build-dependencies]
napi-build = "2.*"
