name: 'alshdavid/setup-just'
description: "Install Just"

inputs:
  version:
    description: 'Just version'
    default: "1.26.0"

runs:
  using: 'composite'
  steps:
    - name: "Install Just" 
      if: ${{ runner.os != 'Windows' }}
      shell: bash
      env:
        NODE_VERSION: ${{ inputs.version }}
      run: "bash .github/workflows/platform/unix/install-just.bash"

    - name: "Install Just" 
      if: ${{ runner.os == 'Windows' && runner.arch == 'X64' }}
      shell: powershell
      env:
        NODE_VERSION: ${{ inputs.version }}
      run: . .github/actions/setup-just/install-just.ps1

    - name: "Install Just" 
      if: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' }}
      shell: powershell
      env:
        NODE_VERSION: ${{ inputs.version }}
      run: exit 1
