[package]
name = "libmach"
version = "0.1.0"
edition = "2021"

[lib]
name = "libmach"

[dependencies]
async-trait = "^0.1.77"
serde = { version = "^1.0.196", features = ["derive"] }
sha2 = { version = "^0.10.8", features = [] }
