name: 'alshdavid/setup-nodejs'
description: "Install Nodejs"

inputs:
  version:
    description: 'Nodejs version'
    default: "22.2.0"

runs:
  using: 'composite'
  steps:
    - name: "Install Nodejs" 
      if: ${{ runner.os != 'Windows' }}
      shell: bash
      env:
        NODE_VERSION: ${{ inputs.version }}
      run: "bash .github/actions/setup-nodejs/install-nodejs.bash"

    - name: "Install Nodejs" 
      if: ${{ runner.os == 'Windows' && runner.arch == 'X64' }}
      shell: powershell
      env:
        NODE_VERSION: ${{ inputs.version }}
      run: . .github/actions/setup-nodejs/install-nodejs.ps1

    - name: "Install Nodejs" 
      if: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' }}
      shell: powershell
      env:
        NODE_VERSION: ${{ inputs.version }}
      run: exit 1

