[package]
name = "libmach"
version = "0.1.0"
edition = "2021"

[lib]
name = "libmach"

[features]
hash = ["dep:sha2"]
serde = ["dep:serde"]

[dependencies]
serde = { version = "^1.0.196", features = ["derive"], optional = true }
sha2 = { version = "^0.10.8", features = [], optional = true }
