name: New Publish
# on: workflow_dispatch
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  - name: Generate Vars
    id: vars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "branch_name=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          echo "bin_hash=$(git ls-files crates/mach | xargs sha256sum | cut -d" " -f1 | sha256sum | cut -d" " -f1) >> $GITHUB_OUTPUT
          echo "npm_hash=$(git ls-files npm/mach | xargs sha256sum | cut -d" " -f1 | sha256sum | cut -d" " -f1) >> $GITHUB_OUTPUT

  - name: Print Vars
    runs-on: ubuntu-latest
    needs: [vars]
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ steps.vars.outputs.branch_name }}"
          echo "${{ steps.vars.outputs.bin_hash }}"
          echo "${{ steps.vars.outputs.npm_hash }}"
  