name: New Publish
# on: workflow_dispatch
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps[0].outputs.branch_name }}
      bin_hash: ${{ steps[0].outputs.bin_hash }}
      npm_hash: ${{ steps[0].outputs.npm_hash }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "branch_name=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          echo "bin_hash=$(git ls-files crates/mach | xargs sha256sum | cut -d" " -f1 | sha256sum | cut -d" " -f1) >> $GITHUB_OUTPUT
          echo "npm_hash=$(git ls-files npm/mach | xargs sha256sum | cut -d" " -f1 | sha256sum | cut -d" " -f1) >> $GITHUB_OUTPUT

  print-variables:
    runs-on: ubuntu-latest
    needs: [vars]
    steps:
      - uses: actions/checkout@v4
      - name: Print Variables
        run: |
          echo "${{ vars.output.branch_name }}"
          echo "${{ vars.output.bin_hash }}"
          echo "${{ vars.output.npm_hash }}"
  