name: New Publish
# on: workflow_dispatch
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.step1.outputs.branch_name }}
      bin_hash: ${{ steps.step1.outputs.bin_hash }}
      npm_hash: ${{ steps.step1.outputs.npm_hash }}
    steps:
      - uses: actions/checkout@v4
      - id: step1
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          BIN_HASH=$(git ls-files crates/mach | xargs sha256sum | cut -d" " -f1 | sha256sum | cut -d" " -f1)
          NPM_HASH=$(git ls-files npm/mach | xargs sha256sum | cut -d" " -f1 | sha256sum | cut -d" " -f1)
          NPM_TAG=$BRANCH_NAME
          if [ $NPM_TAG = "main" ]; then
            NPM_TAG="latest"
          fi

          NPM_TARBALL=node -e "\
            console.log(JSON.parse('$(curl -s https://registry.npmjs.org/@alshdavid/mach/${NPM_TAG})' || {})?.dist?.tarball || '')\
          "

          echo $NPM_TARBALL
          
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "BIN_HASH=$BIN_HASH" >> $GITHUB_OUTPUT
          echo "NPM_HASH=$NPM_HASH" >> $GITHUB_OUTPUT
          echo "NPM_TAG=$NPM_TAG" >> $GITHUB_OUTPUT
